### ISSUE TITLE
[BUG] Does not work in Unity 2018.3

### ISSUE THREAD

**Issue by rafaelbenavent** [AdamRamberg/unity-atoms#164]
Using Unity 2018.3:

Library\PackageCache\com.mambojambostudios.unity-atoms-core@4.1.0\Editor\Drawers\VariableDrawer.cs(6,47): error CS0246: The type or namespace name 'AtomDrawer<>' could not be found (are you missing a using directive or an assembly reference?)

The problem is the AtomDrawer has compiler directives specifying Unity 2018.4 or greater.

**Comment by AdamRamberg** [comment]
Thanks for submitting this issue. Will be addressed in the next release of Unity Atoms.
